/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qrcodes;
import google.googleinfo;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.text.Format;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author RAJENDRA
 */
interface defaultinter{
    
    void profile();
    default void tools()
    {
        System.out.println("This is default interfaces");
    }
}

class project implements defaultinter{
    
    public void profile(){
        
        System.out.println("This is dummy default interface");
    }
}
class objpassing{
    int x;
    objpassing(){
        
        this.x = 10;
    }
    
    
    objpassing(objpassing a){
        
        this.x = a.x;
    }
}
class ReturnObjectDemo{
    int a;
 
    ReturnObjectDemo(int i) { a = i; }
 
    // Method returns an object
    ReturnObjectDemo incrByTen(){
        
        ReturnObjectDemo temp
            = new ReturnObjectDemo(a + 10);
        return temp;
    }
}
class OverRidding{

      void disp(){

    System.out.println("i provide the green color");

   }

}

class Children extends OverRidding{
        @Override
  void disp(){

   System.out.println("i provide red color");

   }
}

class maps{  
 synchronized void printmaps(int n){//synchronized method  
     
   for(int i=1;i<=5;i++){  
     System.out.println(n*i);  
     
     try{  
      Thread.sleep(400);  
     }catch(Exception e){System.out.println(e);}  
   }  
  
 }  
}  
  
class MyThread1 extends Thread{  
maps t;  
MyThread1(maps t){  
this.t=t;  
}  
public void run(){  
t.printmaps(5);  
System.out.println("-----------------------------------------------------------------------");
}  
  
}  
class MyThread2 extends Thread{  
maps t;  
MyThread2(maps t){  
this.t=t;  
}  
public void run(){  
t.printmaps(100);  
  System.out.println("-----------------------------------------------------------------------");
}  
}
class meException extends Exception{
     meException(String s) {
        super(s);
    }
}

class chrome
        {
    int x = 0;
    chrome()
    {
        //this.x = a;
        System.out.println("The value is "+this.x);
        
    }
}
class chrome1 extends chrome
{
    chrome1(){
        
        System.out.println("Level 1 class");
     
    }
   chrome1(int t)
   {
       this.x = t;
       System.out.println("Level 1 class with one parameter");
   }
}
class chrome2 extends chrome1
{
    int s;
    chrome2()
    {
        super();
        
    }
    chrome2(int a)
    {
        
    this.s= a;
    }
}

public class Qr extends javax.swing.JFrame {

    /**
     * Creates new form Qr
     */
    public Qr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        link = new javax.swing.JTextField();
        jbutton1 = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QR CODE ");

        jLabel2.setText("ENTER LINK   :");

        jbutton1.setText("SUBMIT ");
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        jbutton2.setText("CLEAR");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jbutton1)
                                .addGap(34, 34, 34)
                                .addComponent(jbutton2)
                                .addGap(43, 43, 43)
                                .addComponent(jButton3)
                                .addGap(0, 71, Short.MAX_VALUE))
                            .addComponent(link))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton1)
                    .addComponent(jbutton2)
                    .addComponent(jButton3))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
        // TODO add your handling code here:
        try{
                String QrcodeData = link.getText();
                String filepath = "C:\\Users\\user\\Downloads\\QRcodes\\qr.png";
                 String charset= "UTF-8";
           Map <EncodeHintType,ErrorCorrectionLevel> hintMap= new HashMap <EncodeHintType,ErrorCorrectionLevel> ();
                hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
                BitMatrix matrix=new MultiFormatWriter().encode(
                new String(QrcodeData.getBytes(charset),charset),
                            BarcodeFormat.QR_CODE,800,400,hintMap);//i
        
    MatrixToImageWriter.writeToFile(matrix, filepath.substring(filepath.lastIndexOf('.')+1),new File(filepath));
        System.out.println("Qr code has been generated at the location "+filepath);
         JFrame frame = new JFrame();
          ImageIcon icon = new ImageIcon("C:\\Users\\user\\Downloads\\QRcodes\\qr.png");
          JLabel label = new JLabel(icon);
        frame.add(label);
  frame.setDefaultCloseOperation
         (JFrame.EXIT_ON_CLOSE);
  frame.pack();
  frame.setVisible(true);    
        
        
                
        }
        catch(Exception e)
        {
            System.out.println("Invalid link "+e);
        }
        
    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
        // TODO add your handling code here:
        link.setText("");
        link.grabFocus();
        
        
    }//GEN-LAST:event_jbutton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
         defaultinter obj = new project();
        obj.profile();
        
        objpassing ob1 = new objpassing();
        System.out.println("This is illustration of Passing object");
        objpassing ob2 = new objpassing(ob1);
        
         ReturnObjectDemo object1 = new ReturnObjectDemo(2);
         System.out.println("This is illustration of return a object");
        ReturnObjectDemo object2;
 
       object2 = object1.incrByTen();
 
        System.out.println("object1.a: " + object1.a);
        System.out.println("object2.a: " + object2.a);
        
        System.out.println("This is a illustration of overriding line number 61");
        Children over=new Children();
        over.disp();
        
        System.out.println("-----------------------------------------------------------------------");
        System.out.println("USING FUNCTION FROM DIFFERENT PACKAGE: ");
        googleinfo prasad=new googleinfo();
        prasad.currentstatus();
        
         googleinfo preethu=new googleinfo();
         preethu.companyapp();
         
            System.out.println("-----------------------------------------------------------------------");
            
             chrome2 ob3 = new chrome2(122);
              chrome2 ob4 = new chrome2();
               int j = 10;
                try{
                int w = j/10;
                System.out.println(w);
                    throw new meException("Custom Exception is done here");
                  }
                catch(Exception e)
               {
                System.out.println(e);
                System.out.println(e.getMessage());
              }
                
            System.out.println("-----------------------------------------------------------------------");    
            System.out.println("Thread synchronisation");
            maps obj6 = new maps();//only one object  
            MyThread1 t1=new MyThread1(obj6);  
            MyThread2 t2=new MyThread2(obj6);  
            t1.start();  
            t2.start();  

    
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JTextField link;
    // End of variables declaration//GEN-END:variables
}
